### ISSUE TITLE
Editar processo seletivo

### ISSUE THREAD

**Issue by patriciatersariol** [aceleradora-TW/acelera-mais-api#16]
Eu como Mentora Operacional Autenticada
Quero editar um processo seletivo
Para realizar alterações nos dados de um processo já existente

### Critérios - Frontend

- Ao clicar no botão **editar** (cada processo tem o seu botão) :

   - Devo ver uma tela **modal** com um formulário;
   
   - **Formulário** de edição deve conter os seguintes atributos:
   
      - Nome (**campo obrigatório**)
      - Data de início (**campo obrigatório**)
      - Data de término
      - Descrição
      
   - A tela deve exibir três botões:
      - Excluir
      - Cancelar
      - Salvar
      
 - Ao clicar em **salvar**, deve ser feita uma requisição para o endpoint de editar, passando o id e os novos dados do processo: 
  {
   "id": 5, 
   "nome": "novo nome", 
   "startDate": "10/12/2021", 
   "endDate": "10/02/2022", 
   "description": "nova descrição"
   }

- O usuário deve receber uma mensagem de sucesso ou erro (caso passe datas inválidas e/ou nome/data de início vazios)
- Ao clicar em **excluir**, deve ser feita uma confirmação ao usuário: "Você tem certeza?". Caso clique em "não", o usuário volta para a modal de edição. Caso clique em "sim", é feita uma requisição para o endpoint de excluir, passando o id do processo. O usuário deve receber mensagem de erro ou sucesso. 
- Ao clicar em **cancelar**, a modal se fecha e o usuário visualiza a listagem de processos novamente.

**Comment by narukaioh** [comment]
Um tutorial de como pode ser implementada uma Modal

https://medium.com/tinyso/how-to-create-a-modal-component-in-react-from-basic-to-advanced-a3357a2a716a
