### ISSUE TITLE
API: Obter desafio por ID - GET /exercise/:id

### ISSUE THREAD

**Issue by Jojorel** [aceleradora-TW/acelera-mais-api#47]
Eu como **mentora** 
Preciso ver o **desafio** e seus **detalhes** 
pelo **ID** especifico

### Critérios

- Suporte a método **GET** por meio de **ID** do processo;
- Devemos uma criar uma função que busque um desafio pelo **ID** e retorne para o front; 
- Exemplo de URL: localhost:9000/exercise/id;

- Caso o desafio seja encontrado, a API deve devolver um objeto do tipo: 
    
```
   {
    id: Number,
    name: String,
    status: String, // "none", "preparing" ou "done"
    type: String, // "backend", "frontend" ou "fullstack"
    description: String,
    candidate: Object,
    links: {
        pdf: String,
        zip: String,
        github: String
    },
    evaluation: {
        mentorName: String,
        score: Number,
        feedback: String
    }
}
```

- Caso o desafio não seja econtrado, a API deve devolver um objeto do tipo:

```
  {
      "message": “Não foi possível encontrar o desafio!” 
   }
```

PS: Já tem arquivo que define as mensagens.

**Comment by ErickCardoso007** [comment]
Eu como mentora preciso ver os desafios postados pelas candidatas 

# Critérios
- inicialmente precisamos ver os desafios das candidatas, e isso será implementado no backend
- devemos acrescentar um export da função do backend, de forma que receba os desafios
- temos uma dependencia do card de #46 api listagens dos desafios porque primeiramente devemos listalos para depois visualiza-los
- para desenvolve-lo precisamos da lógica necessária para visualização dos desafios

# Objetivo

- [ ] visualizar desafio feito pela listagem dos mesmos 
- [ ] verificar no export da função no backend feito pelo card #46 e adaptalo para os mesmos fins

**Comment by Jojorel** [comment]
@aolchik Ola tudo bem ? pode dar um feedback pra gente nessa questão ?

- Caso o desafio seja encontrado deve devolver a { "id","name","link","candidata_id","hiringProcess_id" ,"review","nota"}

Para identificar os possiveis critérios do desafio, quais que podemos deixar ali.

**Comment by Jojorel** [comment]
@patriciatersariol Nos ajudou e muito no desenvolvimento da especificação.

**Comment by patriciatersariol** [comment]
@Jojorel, atualizei o objeto a ser retornado a partir do contrato definido hoje na planning.
