### ISSUE TITLE
API: Salvar nova avaliação

### ISSUE THREAD

**Issue by LuizHenrique000** [aceleradora-TW/acelera-mais-api#48]
Critérios:
===
Eu como mentora avaliadora
Quero salvar uma nova avaliação no banco de dados
Para então finalizar a etapa do card #36 

Para isso precisaremos:
---
- Ter um endpoint que irá gravar as avaliações, podemos o chamar de /feedback
- Suporte a requisições do tipo POST em /feedback
- Enviar os dados da avaliação ( feedback, nota, mentora que avaliou )

Tasks
===

- [x] Criar uma tabela no banco de dados chamada Avaliacoes para guardar os campos que serão enviados
- [x] Os campos enviados serão: feedback, avaliador, pontuação. Cada um representará uma coluna dentro da tabela Avaliacoes
- [x] Ter um endpoint que irá gravar as avaliações, chamado `/feedback`
- [x] Suporte a request do tipo `POST` em  `/feedback`
- [x] Enviar os dados da avaliação para o banco de dados

**Comment by narukaioh** [comment]
Na real gente, vamos ter que mudar um pouco a estratégia desse card, pois esse endpoint de feedback nao vai existir. No final de tudo, vai ser tudo resumido em exercícios. Essa função salvar feedback, vai ser na verdade um metodo PATCH em `/exercise`
